name: CI Workflow

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  ci-workflow:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo
        env:
          MONGO_INITDB_ROOT_USERNAME: test
          MONGO_INITDB_ROOT_PASSWORD: password
          MONGO_INITDB_DATABASE: test
        ports:
          - 27017:27017
        options: >-
          --health-cmd "echo 'db.runCommand("ping").ok' | mongosh --quiet"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x

    - name: Build Application (SCA)
      run: |
        npm install
        npm install eslint@latest eslint-plugin-security@latest --save-dev

    - name: Run ESLint (SAST)
      run: npx eslint .

    - name: Run app
      run: |
        node index.js &
        npx wait-on http://localhost:8888
      env:
        FRONTEND_URL: "http://localhost"
        JWT_SECRET: "randomstring"
        MONGODB_URI: mongodb://localhost:27017
        MONGODB_DB_NAME: test

    - name: ZAP Baseline Scan
      uses: zaproxy/action-baseline@v0.14.0
      with:
        target: 'http://localhost:8888/'
        allow_issue_writing: false

    - name: Stop App
      run: |
        kill $(lsof -t -i:8888)
